"""initial

Revision ID: 637dc4e08c2a
Revises: 
Create Date: 2026-05-07 21:50:45.819618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '637dc4e08c2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('term_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_name', sa.String(length=100), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('term_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('add_drop_deadline', sa.Date(), nullable=True),
    sa.Column('withdrawal_deadline', sa.Date(), nullable=True),
    sa.Column('final_exam_start_date', sa.Date(), nullable=True),
    sa.Column('final_exam_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('term_code')
    )
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_code', sa.String(length=10), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('building_code')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_code', sa.String(length=10), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_faculty_id', sa.UUID(), nullable=True),
    sa.Column('parent_department_id', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_faculty_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_code'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('equipment', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('user_personal_info',
    sa.Column('info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('info_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_role_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('course_level', sa.String(length=20), nullable=True),
    sa.Column('lecture_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('lab_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_outcomes', sa.Text(), nullable=True),
    sa.Column('syllabus_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('faculty_rank', sa.String(length=50), nullable=False),
    sa.Column('tenure_status', sa.String(length=30), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('office_room_id', sa.Integer(), nullable=True),
    sa.Column('office_hours', sa.Text(), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('specializations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('teaching_load_credits', sa.Integer(), nullable=True),
    sa.Column('max_advisees', sa.Integer(), nullable=True),
    sa.Column('current_advisees', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['office_room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('faculty_id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_code', sa.String(length=20), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('degree_level', sa.String(length=50), nullable=False),
    sa.Column('duration_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('total_credits_required', sa.Integer(), nullable=False),
    sa.Column('program_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_per_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('accreditation_status', sa.String(length=50), nullable=True),
    sa.Column('accreditation_body', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('program_code')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_category', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('office_room_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('salary_grade', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['office_room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('course_sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('enrolled_count', sa.Integer(), nullable=True),
    sa.Column('waiting_list_count', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('schedule_pattern', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('syllabus_url', sa.Text(), nullable=True),
    sa.Column('join_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('expected_graduation_date', sa.Date(), nullable=True),
    sa.Column('actual_graduation_date', sa.Date(), nullable=True),
    sa.Column('current_term_id', sa.Integer(), nullable=True),
    sa.Column('academic_standing', sa.String(length=50), nullable=True),
    sa.Column('enrollment_status', sa.String(length=50), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('cumulative_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_credits_earned', sa.Integer(), nullable=True),
    sa.Column('total_credits_attempted', sa.Integer(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('visa_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_term_id'], ['academic_terms.term_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_number')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('assignment_name', sa.String(length=200), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('late_submission_allowed', sa.Boolean(), nullable=True),
    sa.Column('late_penalty_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submission_type', sa.String(length=30), nullable=True),
    sa.Column('rubric_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_group_assignment', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('arrival_time', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('enrollment_status', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('grade_points', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('midterm_grade', sa.String(length=5), nullable=True),
    sa.Column('final_grade', sa.String(length=5), nullable=True),
    sa.Column('grade_submitted_date', sa.DateTime(), nullable=True),
    sa.Column('grade_submitted_by', sa.UUID(), nullable=True),
    sa.Column('is_audit', sa.Boolean(), nullable=True),
    sa.Column('withdrawal_date', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_submitted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.section_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('student_accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('total_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_payments', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_credits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_hold', sa.Boolean(), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('assignment_submissions',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('submission_url', sa.Text(), nullable=True),
    sa.Column('submission_text', sa.Text(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.UUID(), nullable=True),
    sa.Column('graded_date', sa.DateTime(), nullable=True),
    sa.Column('submission_status', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('assignment_teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('financial_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversal_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['student_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_transaction_id'], ['financial_transactions.transaction_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('assignment_team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['assignment_teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_team_members')
    op.drop_table('financial_transactions')
    op.drop_table('assignment_teams')
    op.drop_table('assignment_submissions')
    op.drop_table('student_accounts')
    op.drop_table('enrollments')
    op.drop_table('attendance')
    op.drop_table('assignments')
    op.drop_table('students')
    op.drop_table('course_sections')
    op.drop_table('staff')
    op.drop_table('programs')
    op.drop_table('faculty')
    op.drop_table('courses')
    op.drop_table('user_role_assignments')
    op.drop_table('user_personal_info')
    op.drop_table('rooms')
    op.drop_table('departments')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('buildings')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
